title: "Eloy Salamanca"
email: info@eloysalamanca.es
timezone: Europe/Madrid
baseurl: ""
permalink: "/:categories/:slug/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: eloy
paginate: 10
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: "G-D3YWTXZV4Q"

# Comments
comments:
  provider: "giscus"
  giscus:
    repo                 : "eloy-salamanca/eloy-salamanca.github.io"
    repo_id              : "R_kgDOLFrWUA"
    category             : "Announcements"
    category_id          : "DIC_kwDOLFrWUM4Ccefp"
    mapping              : "pathname" # (default), "url", "title", "og:title"
    reactions_enabled    : '1' # for enabled (default), '0' for disabled
    metadata             : '1'
    theme                : "light" # (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
#disqus: #'demowebsite'

# Authors
authors:
  eloy:
    name: Eloy
    display_name: Eloy Salamanca
    avatar: 'assets/images/eloy.png'
    email: info@eloysalamanca.es
    web: https://eloysalamanca.es/
    twitter: https://twitter.com/EloySalamancaR
    description: ""

# Social
social:
  linkedin: https://linkedin.com/in/eloysalamanca
  instagram: #https://www.instagram.com/bootstrapstarter/
  facebook: #https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/EloySalamancaR
  envelope: mailto:info@eloysalamanca.es

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-D3YWTXZV4Q"
    anonymize_ip         : false

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives